name: CI/CD Pipeline

on:
  push:
    branches:
      - desarrollo
      - pruebas
      - produccion
  pull_request:
    branches:
      - desarrollo
      - pruebas
      - produccion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Aquí puedes agregar más pasos según tus necesidades
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build
